# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Marco Gallardo
title: Automation Engineer
email: mrcogllrdo@berkeley.edu
website: https://marcgallard.github.io/My-Page/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  marcgallard
linkedin_username: marcgallard

# Additional icon links
additional_links:
- title: kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/mrcogllrdo
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Marco and I'm an automation engineer. As well as automating systems I also have experience visualizing data (currently focusing on geospatial data), designing and coding ETL processes/workflows, designing and setting up databases with MySql and MongoDB, data science work (including a case study in R on my Kaggle's page), and cybersecurity (I worked as a security engineer and took some security courses). I have worked at a number of companies, gaining teamwork and leadership skills in the process. I am looking for work that involves data science, though I am open to other roles.

  I am most skilled in: <mark>Python</mark>, <mark>APIs</mark>, <mark>Data structures</mark>, and <mark>Scientific computing</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: EONET Event Visualizer
        link: github.com/marcgallard
        # link_text: Blank
        additional_links:
          - title:  EONET Event Visualizer Repo
            icon: fab fa-github
            url: https://github.com/marcgallard/EONETEventVisualizer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Visualizes global events and disasters using Tableau Public, data collected using NASA's EONET API
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of refreshing my <mark>Python</mark> skills and to practice visualizing data, particularly geospatial data as I've never worked with it before. I have learned a few new skills through this, such as creating a dashboard on Tableau Public. Please feel free to play around with it, the link is posted on the repo page!
      - layout: top-middle
        title: BMI Calculator
        link: github.com/marcgallard
        # link_text: Blank
        additional_links:
          - title:  BMI Calculator
            icon: fab fa-github
            url: https://github.com/marcgallard/code-20220915-marcogallardo
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          BMI calculator that takes in JSON data meeting a specified format which is then categorized according to a given JSON table.
        description: | # this will include new lines to allow paragraphs
          This was originally a response to a coding question given by a job I applied to in the past. The goal was to create a BMI calculator in <mark>Python</mark> to accept basic health data of several patients in JSON format which can then be used to determine their BMI, its respective category, and associated health risk. The inclusion of a JSON schema and BMI table allows flexibility for how the code can be used.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professional and Wellness Sabbatical
        caption: February 2022 - April 2023
        quote: >
          Took an extended sabbatical to focus on myself
        description: | # this will include new lines to allow paragraphs
          - Earned a Google Data Analytics Certificate from a 24-week Coursera course that taught data analysis and cleaning; completed a Fitabit case study in R and uploaded the write-up to Kaggle
          - Took an intro project management course on Coursera to better address project managers’ needs
          - Visualized EONET data from NASA using Tableau, Python, and EONET API; interactive dashboard and code found on GitHub
      - layout: left
        title: Armature Systems
        link: https://www.armaturesystems.com/
        sub_title: Automation Engineer
        caption: May 2021 - Jan 2022
        quote: >
          Provides years of cross-functional experience in Security, Automation, Networking, and Wireless to help deliver secure, reliable, fast, and scalable networks.
        description: | # this will include new lines to allow paragraphs
            - API based custom integrations and scripting
            - Planned, developed, and tested a suite of (primarily Python) scripts that communicated with servers running Palo Alto's Panorama to automate firewall management; utilized PAN-OS SDK, REST API with Postman for testing, and CLI
            - Participated in multiple change windows, several times a week, alongside senior engineers to manage 150+ devices. Coordinated review of made and planned changes with internal network engineers to determine next change window’s workflow
            - Collected, cleaned, and processed data for determining KPIs
            - Limited SOAR automation (Demisto/Cortex XSoar)
            - Utilized MongoDB to store, filter, and retrieve network assets
      - layout: left
        title: Geek Girl Tech
        link: https://geekgirltech.com/
        sub_title: Security Engineer
        caption: Sep 2020 - Apr 2021
        quote: >
          Provides cyber security & IT support for small to mid-sized socially conscious companies.
        description: | # this will include new lines to allow paragraphs
            - Assisted in conducting risk assessments and security audits per ISO/IEC 27001, NIST SP 800-171, GLBA, and IRS 4557 to ensure clients met state, federal, and industry compliance requirements.
            - Responsible for setting up, onboarding, and managing clients' JumpCloud directory services, Google Workspace, Duo Security, and RMM agent to provide IT administration support to ~200 users.
            - Customized and crafted security strategies, programs, and awareness training via InfoSec IQ to improve overall security posture and user education for new clients.
            - Developed and maintained effective communication and working relationships with customers.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California - Berkeley
        caption: 2015 - 2019
        sub_title: BSc Electrical Engineering and Computer Science
        quote: >
          The University of California was founded in 1868, born out of a vision in the State Constitution of a university that would “contribute even more than California’s gold to the glory and happiness of advancing generations.”
        description: | # this will include new lines to allow paragraphs
          During my time at UC Berkeley, I learned most of my key skills that I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and still keep in touch with some of the friends I've made during my time there.
      - layout: left
        title: NPower
        caption: Feb 2019 - Jul 2019
        sub_title: Networking & Security Administration Program
        quote: >
          Attended a nonprofit’s 18-week long IT course geared for veterans and underserved minorities
        description: | # this will include new lines to allow paragraphs
            - Practiced implementation of routing protocols such as RIP and OSPF through Cisco’s CLI using Packet Tracer
            - Monitored and analyzed network traffic using tools such as Wireshark and NetFlow, as well as understanding current encryption standards and technologies
            - Led a team of 5 against 3 other teams for a week-long point-based competition within the course reviewing all material and won 1st place by more than 20% of point total compared to 2nd
  - title: Licenses and Certifications
    layout: list
    content:
      - layout: left
      title: Google Data Analytics Certificate
      caption: Issued March 2023
      sub_title: Issued by Coursera
      description: Can be verified at https://www.credly.com/badges/c8758c6f-22c8-4836-9ee5-8cecd8ddad5d/linked_in_profile
      - layout: left
      title: CompTIA Security+
      caption: Issued May 2019, Expired May 2022
      sub_title: Issued by CompTIA
      description: Can be verified at http://verify.CompTIA.org with ID 65SKH4NMSHQQQ590
      - layout: left
      title: CompTIA IT Fundamentals+
      caption: Issued September 2019
      sub_title: Issued by CompTIA
      description: Can be verified at http://verify.CompTIA.org with ID BS4CM9JE6PQQQQCV
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interest in programming, some of my other interests and hobbies are:
      - Bouldering
      - Gaming
      - Reading (mostly about Buddhism and Hinduism)
      - Keeping up-to-date with the latest developments in AI

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
