# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Marco Gallardo
title: Direct Support Professional
email: mrcogllrdo@berkeley.edu
website: https://marcgallard.github.io/My-Page/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  marcgallard
linkedin_username: marcgallard

# Additional icon links
additional_links:
- title: kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/mrcogllrdo
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Marco and I'm an engineering and IT professional with a UC Berkeley degree transitioning to the healthcare industry. My tech background consists of: automating systems, visualizing and analyzing data, designing and coding ETL processes/workflows, designing and setting up databases, IT support, and cybersecurity (I worked as a security engineer and took some security courses). I have worked at a number of companies, gaining teamwork and leadership skills in the process.

  While I'm still interested in tech as a hobby, I have also begun to explore other fields that focuses more on interactions outside of the digital medium. The industry that has captured my attention since then has been healthcare. My last job, direct support professional, has inspired me to seek roles that focuses on serving others in a manner that directly enriches their lives. I am still open to roles that involve tech in some form, and I am also focusing my efforts on becoming a future medical professional (either RN or CAA). Please feel free to contact me with roles you think I'd be interested in!

  For my tech skillset, I am most skilled in: <mark>Python</mark>, <mark>APIs</mark>, <mark>Data structures</mark>, and <mark>Scientific computing</mark>. 
  
  For my soft skillset, I am most skilled in: <mark>De-escalation</mark>, <mark>Effective Communication</mark>, <mark>Teamwork</mark>, <mark>Customer Service</mark>, <mark>Caregiving</mark>, and <mark>Leadership</mark>.
  
  Please refer to the bottom of this page for my recent certifications.

content:
  - title: Tech Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: EONET Event Visualizer
        link: github.com/marcgallard
        # link_text: Blank
        additional_links:
          - title:  EONET Event Visualizer Repo
            icon: fab fa-github
            url: https://github.com/marcgallard/EONETEventVisualizer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Visualizes global events and disasters using Tableau Public, data collected using NASA's EONET API
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of refreshing my <mark>Python</mark> skills and to practice visualizing data, particularly geospatial data as I've never worked with it before. I have learned a few new skills through this, such as creating a dashboard on Tableau Public. Please feel free to play around with it, the link is posted on the repo page!
      - layout: top-middle
        title: BMI Calculator
        link: github.com/marcgallard
        # link_text: Blank
        additional_links:
          - title:  BMI Calculator
            icon: fab fa-github
            url: https://github.com/marcgallard/code-20220915-marcogallardo
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          BMI calculator that takes in JSON data meeting a specified format which is then categorized according to a given JSON table.
        description: | # this will include new lines to allow paragraphs
          This was originally a response to a coding question given by a job I applied to in the past. The goal was to create a BMI calculator in <mark>Python</mark> to accept basic health data of several patients in JSON format which can then be used to determine their BMI, its respective category, and associated health risk. The inclusion of a JSON schema and BMI table allows flexibility for how the code can be used.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RES Success
        link: https://www.ressuccess.org/
        sub_title: Direct Support Professional
        caption: November 2023 - June 2024
        quote: >
          The organization supports adults with intellectual and developmental disabilities with day programs that build dignity and independence in a context of kindness. We help the people we support connect with their communities and pursue the goals and dreams that matter most to them.
        description: | # this will include new lines to allow paragraphs
          - Aided adults (groups of 3-4) with cognitive disabilities on implementing their Individual Service Plans (ISPs) while building public navigational skills
          - Provided training and support in behavior management, social etiquette, and utilization of public resources on a daily basis
          - Practiced a person-centered approach to care while developing others’ higher level of independence
          - Documented client’s progress and needs in daily reports while providing personal daily living assistance and support
      - layout: left
        title: Professional and Wellness Sabbatical
        caption: February 2022 - April 2023
        quote: >
          Took an extended sabbatical to focus on myself and my goals amidst COVID
        description: | # this will include new lines to allow paragraphs
          - Earned a Google Data Analytics Certificate from a 24-week Coursera course that taught data analysis and cleaning; completed a Fitabit case study in R and uploaded the write-up to Kaggle
          - Took an intro project management course on Coursera to better address project managers’ needs
          - Completed several programming projects; refer to "Tech Projects" section for some examples
      - layout: left
        title: Armature Systems
        link: https://www.armaturesystems.com/
        sub_title: Automation Engineer
        caption: May 2021 - Jan 2022
        quote: >
          Provides years of cross-functional experience in Security, Automation, Networking, and Wireless to help deliver secure, reliable, fast, and scalable networks.
        description: | # this will include new lines to allow paragraphs
            - API based custom integrations and scripting
            - Planned, developed, and tested a suite of (primarily Python) scripts that communicated with servers running Palo Alto's Panorama to automate firewall management; utilized PAN-OS SDK, REST API with Postman for testing, and CLI
            - Participated in multiple change windows, several times a week, alongside senior engineers to manage 150+ devices. Coordinated review of made and planned changes with internal network engineers to determine next change window’s workflow
            - Collected, cleaned, and processed data for determining KPIs
            - Limited SOAR automation (Demisto/Cortex XSoar)
            - Utilized MongoDB to store, filter, and retrieve network assets
      - layout: left
        title: Geek Girl Tech
        link: https://geekgirltech.com/
        sub_title: Security Engineer
        caption: Sep 2020 - Apr 2021
        quote: >
          Provides cyber security & IT support for small to mid-sized socially conscious companies.
        description: | # this will include new lines to allow paragraphs
            - Assisted in conducting risk assessments and security audits to ensure clients met state, federal, and industry compliance requirements
            - Responsible for setting up, onboarding, and managing clients' IT infrastructure (such as JumpCloud directory services, Google Workspace, Duo Security, and installing RMM agents) to provide IT administration support to ~200 users.
            - Customized and crafted security strategies, programs, and awareness training via InfoSec IQ to improve overall security posture and user education for new clients.
            - Developed and maintained effective customer communication and relationships through email, Zoom check-ins, and IT Support sessions
            - Troubleshot software and hardware for clients, the latter of which sometimes consisted of: disassembling hardware, diagnosing the problem, then re-assembling the device into working condition

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California - Berkeley
        caption: 2015 - 2019
        sub_title: BSc Electrical Engineering and Computer Science
        description: | # this will include new lines to allow paragraphs
          During my time at UC Berkeley, I learned most of my key skills that I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and still keep in touch with some of the friends I've made during my time there.
      - layout: left
        title: Contra Costa College
        caption: 2024 - Present
        sub_title: Biology coursework for applying to RN programs
        description: | # this will include new lines to allow paragraphs
          I am currently taking pre-requisite coursework to later become an RN (or possibly CAA, still undecided)
      - layout: left
        title: NPower
        caption: Feb 2019 - Jul 2019
        sub_title: Networking & Security Administration Program
        quote: >
          Attended a nonprofit’s 18-week long IT course geared for veterans and underserved minorities
        description: | # this will include new lines to allow paragraphs
            - Practiced implementation of routing protocols such as RIP and OSPF through Cisco’s CLI using Packet Tracer
            - Monitored and analyzed network traffic using tools such as Wireshark and NetFlow, as well as understanding current encryption standards and technologies
            - Led a team of 5 against 3 other teams for a week-long point-based competition within the course reviewing all material and won 1st place by more than 20% of point total compared to 2nd
  - title: Licenses and Certifications
    layout: list
    content:
      - layout: left
        title: Adult First Aid/CPR/AED
        caption: Valid March 2024 to March 2026
        sub_title: Issued by American Red Cross Training Services
        description: Can be verified at https://www.redcross.org/take-a-class/digital-certificate with code 01FVV00
      - layout: left
        title: Person Centered Thinking Training
        caption: Valid April 2024 to April 2028
        sub_title: Issued by Regional Center of the East Bay
        description: PDF of certificate indicating completion available upon request
      - layout: left
        title: Google Data Analytics Certificate
        caption: Issued March 2023
        sub_title: Issued by Coursera
        description: Can be verified at https://www.credly.com/badges/c8758c6f-22c8-4836-9ee5-8cecd8ddad5d/linked_in_profile
      - layout: left
        title: CompTIA Security+
        caption: Issued May 2019, Expired May 2022
        sub_title: Issued by CompTIA
        description: Can be verified at http://verify.CompTIA.org with ID 65SKH4NMSHQQQ590
      - layout: left
        title: CompTIA IT Fundamentals+
        caption: Issued September 2019
        sub_title: Issued by CompTIA
        description: Can be verified at http://verify.CompTIA.org with ID BS4CM9JE6PQQQQCV
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my tech and health interests, some of my other interests and hobbies are:
      - Bouldering (currently on a hiatus)
      - Gaming
      - Reading
      - Spirituality (specifically the intersection of Vajrayana Buddhism, Advaita Vedanta, and Western spirituality)
      - Volunteering at my local animal shelter (I LOVE animals!!)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
